In [1]:
import numpy as np

# Task 1: Creating Arrays 

#1.Write a Python program to:

#Create a 1D NumPy array of 10 integers ranging from 1 to 10.


arr = np.arange(1,11)
print("1D array: ",arr)

#Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.

mat = np.arange(1,10).reshape(3,3)
print("\n2D Array (3x3) with values 1 to 9:\n")
print(mat)

#Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).

Three_d = np.random.rand(3,5,3)
print("\n3d array\n")
print(Three_d)

#2.Display the shape, size, and datatype of each array.

print("1D array 'arr':", arr.shape, arr.size, arr.dtype)
print("2D array 'mat':", mat.shape, mat.size, mat.dtype)
print("3D array 'Three_d':", Three_d.shape, Three_d.size, Three_d.dtype)

1D array:  [ 1  2  3  4  5  6  7  8  9 10]

2D Array (3x3) with values 1 to 9:

[[1 2 3]
 [4 5 6]
 [7 8 9]]

3d array

[[[0.34222124 0.08690345 0.24647287]
  [0.9265898  0.73363195 0.1070271 ]
  [0.63072615 0.33884419 0.2209845 ]
  [0.60738197 0.10430389 0.40152663]
  [0.5243114  0.63584978 0.05346621]]

 [[0.77811173 0.26646258 0.04874484]
  [0.39808508 0.82414872 0.88226578]
  [0.45283669 0.83430019 0.77896977]
  [0.64851436 0.64723014 0.87044514]
  [0.27695783 0.63560656 0.32229227]]

 [[0.8519363  0.49831579 0.87053097]
  [0.8595443  0.61362015 0.34872062]
  [0.21574726 0.58088314 0.49507321]
  [0.15296121 0.1922398  0.30378525]
  [0.74674459 0.6629693  0.18928623]]]
1D array 'arr': (10,) 10 int64
2D array 'mat': (3, 3) 9 int64
3D array 'Three_d': (3, 5, 3) 45 float64


In [2]:
import numpy as np

# Task 2: Array Indexing and Slicing

# 1. Create a NumPy array from the following list:

data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr2 = np.array(data)

# 2. Retrieve the first three elements of the array.

first_three = arr2[:3]
print("First three elements:", first_three)

# Retrieve every alternate element of the array.

alternate_elements = arr2[::2]
print("Every alternate element:", alternate_elements)

# Reverse the array.
reverse = arr2[::-1]
print("Reversed array:", reverse)

First three elements: [10 20 30]
Every alternate element: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


In [3]:
import numpy as np

# Task 3: Mathematical Operations

# 1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.

A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("Array A:", A)
print("Array B:", B)

# 2. Add, subtract, multiply, and divide the two arrays element-wise.

print("\nA + B:", A + B)
print("A - B:", A - B)
print("A * B:", A * B)
print("A / B:", A / B)

# Compute the dot product of the arrays.

print("\nDot product:", np.dot(A, B))

# Find the mean, median, standard deviation, and variance of array A.

print("\nMean of A:", np.mean(A))
print("Median of A:", np.median(A))
print("Standard deviation of A:", np.std(A))
print("Variance of A:", np.var(A))

# Identify the maximum and minimum values in array B and their indices.

print("\nMax of B:", np.max(B), "at index", np.argmax(B))
print("Min of B:", np.min(B), "at index", np.argmin(B))

Array A: [ 2  7 16  5 13]
Array B: [13 18  1 20 11]

A + B: [15 25 17 25 24]
A - B: [-11 -11  15 -15   2]
A * B: [ 26 126  16 100 143]
A / B: [ 0.15384615  0.38888889 16.          0.25        1.18181818]

Dot product: 411

Mean of A: 8.6
Median of A: 7.0
Standard deviation of A: 5.161395160225576
Variance of A: 26.639999999999997

Max of B: 20 at index 3
Min of B: 1 at index 2


In [4]:
import numpy as np

# Task 4: Reshaping and Transposing

# 1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
arr = np.arange(1, 13)
print("1D array: ", arr)

# 2. Reshape the array into a 2D array of shape (4, 3).

arr_2d = arr.reshape(4, 3)
print("\nReshaped to 2D (4x3):\n\n", arr_2d)

# Reshape the array into a 3D array of shape (2, 2, 3).

arr_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 3D (2x2x3):\n\n", arr_3d)

# Transpose the reshaped 2D array and display its shape.
Transpose_2d = arr_2d.T
print("\nTransposed 2D array:\n\n",Transpose_2d )
print("\nShape of transposed 2D array:", Transpose_2d.shape)

1D array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 2D (4x3):

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Reshaped to 3D (2x2x3):

 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Transposed 2D array:

 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

Shape of transposed 2D array: (3, 4)


In [5]:
import numpy as np

# Task 5: Boolean Masking and Filtering

#1. Create a NumPy array with 15 random integers between 10 and 50.

array = np.random.randint(10,51,15)
print("Original Array:\n", array)

#2. Write a Python program to:

# Find all elements greater than 25.

elements = array[array>25]
print("\nElements greater than 25:\n", elements)

# Replace all elements less than 30 with 0.

array[array < 30] = 0
print("\nArray after replacing elements < 30 with 0:\n", array)

# Count the number of elements divisible by 5.

count = np.sum(array % 5 == 0)
print("\nNumber of elements divisible by 5:", count)

Original Array:
 [10 24 15 38 45 31 38 49 41 14 46 25 24 47 40]

Elements greater than 25:
 [38 45 31 38 49 41 46 47 40]

Array after replacing elements < 30 with 0:
 [ 0  0  0 38 45 31 38 49 41  0 46  0  0 47 40]

Number of elements divisible by 5: 8


In [6]:
import numpy as np

# Task 6: Working with Built-in Functions

# 1. Use NumPy's built-in functions to:

# Create an array of 10 equally spaced values between 0 and 1.

arr = np.linspace(0, 1, 10)
print("10 equally spaced values between 0 and 1:\n\n",arr)

# Create an identity matrix of size 4x4.

identity_matrix = np.eye(4, dtype=int)
print("\n4x4 Identity matrix:\n\n", identity_matrix)

# Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

random_arr = np.random.randint(1, 101, 20)
sorted_arr = np.sort(random_arr)
largest_5 = sorted_arr[-5:]

print("\nSorted array of 20 random integers:\n\n", sorted_arr)
print("\n5 largest elements:", largest_5)

10 equally spaced values between 0 and 1:

 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

4x4 Identity matrix:

 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Sorted array of 20 random integers:

 [  1   7   7  14  18  18  23  30  39  45  46  50  53  62  69  70  75  75
  99 100]

5 largest elements: [ 70  75  75  99 100]


In [7]:
import numpy as np
import time

#Task 7: Generic

# 1.Create a Python program that:


# Generate two large random arrays of size (100, 100)

st_time = time.time()
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)



# Perform matrix multiplication

C = np.dot(A,B)

# Find the determinant

det = np.linalg.det(C)

# We can find the inverse if determinant is not zero

if det != 0:
	inv = np.linalg.inv(C)
	print("Inverse calculated successfully.\n")
else:
	inv = None
	print("Matrix is singular, inverse does not exist.")

end_time = time.time()

print("Array 1\n\n", A)
print("\nArray 2\n\n", B)
print("\nDeterminant:", det)
print("\nThe Inverse is", inv)
print("\nTime taken (seconds):", end_time - st_time)

Inverse calculated successfully.

Array 1

 [[0.9251139  0.5236256  0.7554563  ... 0.50275867 0.78180965 0.21553934]
 [0.10792026 0.28955392 0.11772549 ... 0.58845119 0.25600375 0.52169004]
 [0.85585024 0.97848769 0.45452879 ... 0.64175744 0.36132824 0.35669608]
 ...
 [0.67441181 0.15458003 0.14480118 ... 0.69434485 0.22623879 0.96438216]
 [0.1409412  0.73083067 0.42253801 ... 0.29656398 0.67877121 0.98176086]
 [0.23725205 0.95155561 0.95736974 ... 0.73415211 0.0421673  0.17466226]]

Array 2

 [[0.10251332 0.31230352 0.71175355 ... 0.001142   0.3569198  0.45607099]
 [0.70209144 0.77941483 0.26054085 ... 0.24907444 0.22607192 0.22617147]
 [0.02177523 0.53862169 0.17147154 ... 0.73656675 0.10573216 0.00756225]
 ...
 [0.09028563 0.37480346 0.83225334 ... 0.06757573 0.85872047 0.45500543]
 [0.14022369 0.95650813 0.91162863 ... 0.27674949 0.28631508 0.23894284]
 [0.28512966 0.05666433 0.15781739 ... 0.36736487 0.00240662 0.9990762 ]]

Determinant: -8.181258075578938e+49

The Inverse is [[ 1